-- CDC production function-execution hardening.;
-- Tested on isolated Neon branch br-dry-heart-b44tv0ah before production application.;
-- Public website form RPCs remain available; sensitive/admin/server-only helpers are not browser-executable.;
;
ALTER DEFAULT PRIVILEGES FOR ROLE neondb_owner IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE neondb_owner IN SCHEMA app_private REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION app_private.admin_has_role_for_user(text,text[]) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION app_private.is_active_admin_for_user(text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_setup_available() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_admin_change() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.can_manage_gallery_album(uuid) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.can_manage_gallery_album(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.convert_donation_intent_to_donor(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_donation_intent(text,text,text,numeric,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_donation_intent_v2(text,text,text,text,numeric,text,text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_supporter_draft_from_donation(uuid) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_admin_role(text[]) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_active_admin() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_contact_reference() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_donation_reference() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_donor_reference() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_receipt_reference() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_contact_message(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_donation_designation(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_donation_intent(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_donor(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_newsletter_subscriber(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_payment_method(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.permanent_delete_verified_donation(uuid,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.record_gateway_verified_donation(uuid,text,text,timestamptz,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.record_verified_donation(uuid,text,text,timestamptz,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_contact_message_status(uuid,text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_donation_intent_status(uuid,text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_newsletter_subscriber_state(uuid,boolean) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.show_db_tree() FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_contact_message(text,text,text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_contact_message_v2(text,text,text,text,text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.subscribe_newsletter(text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.subscribe_newsletter_v2(text,text) FROM PUBLIC, anonymous, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_gallery_album_cover() FROM PUBLIC, anonymous, authenticated;
GRANT EXECUTE ON FUNCTION app_private.admin_has_role_for_user(text,text[]) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION app_private.is_active_admin_for_user(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_gallery_album(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_gallery_album(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.convert_donation_intent_to_donor(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_supporter_draft_from_donation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_admin_role(text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_active_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_contact_message(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_donation_designation(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_donation_intent(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_donor(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_newsletter_subscriber(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_payment_method(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.permanent_delete_verified_donation(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_verified_donation(uuid,text,text,timestamptz,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_contact_message_status(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_donation_intent_status(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_newsletter_subscriber_state(uuid,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_donation_intent(text,text,text,numeric,text) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION public.create_donation_intent_v2(text,text,text,text,numeric,text,text,text) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_contact_message(text,text,text,text) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_contact_message_v2(text,text,text,text,text,text) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION public.subscribe_newsletter(text) TO anonymous, authenticated;
GRANT EXECUTE ON FUNCTION public.subscribe_newsletter_v2(text,text) TO anonymous, authenticated;
